p-chess/chess

src/Board.php
src/Chess.php
src/Move.php

♻️ refactor Chess to use Board object

---

src/Chess.php
src/Validation.php

Array and string offset access syntax with curly braces is deprecated

🎨 remove deprecated string offset access syntax

---

composer.json
src/Chess.php
src/Move.php
tests/ChessPublicator.php
tests/GameTest.php
tests/MoveTest.php

fix types in Move

---

README.md
composer.json
composer.lock
src/Board.php
src/Chess.php
src/History.php
src/Output/AsciiOutput.php
src/Output/BasicOutput.php
src/Output/OutputInterface.php
src/Output/PgnOutput.php
src/Output/UnicodeOutput.php
src/Piece.php
src/Validation.php
tests/AttackTest.php
tests/ChessPublicator.php
tests/ConstructorTest.php
tests/FenTest.php
tests/MoveTest.php

This moves some code to correct responsibility.

♻️ move some code to Board

---

.php_cs
src/Board.php
src/Chess.php
src/Move.php
src/Output/AsciiOutput.php
src/Output/PgnOutput.php
src/Output/UnicodeOutput.php
src/Piece.php
src/Validation.php
tests/AttackTest.php
tests/ChessPublicator.php
tests/GameTest.php
tests/MiscTest.php
tests/MoveTest.php
tests/PgnTest.php

This should improve performance a bit

⚡️ use native functions

---

composer.json
composer.lock

Before this update, I got following error on php 7.4:
>fgets(): read of 8192 bytes failed with errno=9 Bad file descriptor

⬆️ fix benchmark by upgrading phpbench

---

src/Board.php
src/Chess.php
src/Output/AsciiOutput.php
src/Output/UnicodeOutput.php
src/Piece.php

This is a first step to solve #18 
It avoids to get useless entries in Board array (so, whit proposed change, array contains only the 64 relevant elements, instead of 120 elements).

♻️ improve Board

---

src/Board.php
src/Chess.php
src/Move.php
src/Output/UnicodeOutput.php
src/Piece.php
tests/MoveTest.php
tests/PerftTest.php
tests/PieceTest.php

♻️ improve cache keys

---

src/Board.php
src/Output/AsciiOutput.php
src/Output/BasicOutput.php
src/Output/UnicodeOutput.php
tests/ConstructorTest.php

I think this is an important feature for a game (I mean, black players want to see the board from their point of view, for sure).
Additionally, I simplified a bit the output classes

✨ add an option to reverse board

---

composer.json
src/Board.php
src/Chess.php
src/History.php
src/Move.php
src/Output/PgnOutput.php
tests/ChessPublicator.php
tests/MiscTest.php
tests/MoveTest.php
tests/PgnTest.php

This will likely decrease coverage a bit, since it's really hard to cover edge case (but such cases are caught by phpstan anyway)

🎨 raise phpstan level

---

composer.json
phpstan.neon
src/Board.php
src/Chess.php
tests/AttackTest.php
tests/ConstructorTest.php
tests/FenTest.php
tests/GameTest.php
tests/MiscTest.php
tests/MoveTest.php
tests/PerftTest.php
tests/PgnTest.php
tests/PiecePlacementTest.php
tests/PieceTest.php

This mainly refactors a bit Chess constructor, by simplifying it.
Also, remove public `reset` method, that is almost useless (you can just call `load` instead.
Also, improve a bit code in tests

🎨 improve tests (and remove a public method)

---

src/Chess.php
tests/ChessPublicator.php
tests/MoveTest.php

See issue #27 
In this PR I'm refactoring arguments, leaving out the option of removing them, for now.

🎨 use explicit arguments on generateMoves method

---

README.md
buddy.yml
composer.json
src/Output/ImagineOutput.php
tests/ConstructorTest.php

This can be an interesting feature

✨ add an image-based renderer

---

README.md
src/Output/ImagineOutput.php
tests/ConstructorTest.php

See https://github.com/p-chess/chess/pull/37#issuecomment-806492060

✨ add coordinates to ImagineOutput

---

README.md
docs/output_html.md
src/Board.php
src/Chess.php
src/Output/HtmlOutput.php
src/Output/Link.php
tests/ConstructorTest.php
tests/HtmlOutputStub.php

Yet another output class 😉
This one is a bit more elaborate since you need some additional information to build a functional HTML board.
But I think it's totally worth it: it's a base to build an online Chess game

✨ add HtmlOutput

---

README.md
docs/board.md
docs/chess.md
docs/history.md
docs/index.md
docs/move.md
docs/piece.md
src/Board.php
src/Chess.php
src/Move.php
tests/MoveTest.php

Let's add some docs!
While writing it, I found a couple of improvements to apply in source code:
* the flags bits are related to a move, so they should belong to `Move` (not to `Board`)
* when clearing the board, we should not create 120 squares, but only 64
Side note: after this, what about releasing a tag? Maybe also in "zero" major version (e.g. `0.1.0`)

📝 add more documentation

---

docs/chess.md
docs/history.md
src/Chess.php
src/Entry.php
src/History.php
tests/ChessPublicator.php
tests/ConstructorTest.php
tests/GameTest.php

Yet another array removed and replaced with a real object.

♻️ refactors History

---

docs/output_html.md

Shame on me: I didn't realize that my initial implementation of CSS for HTML board had colors wrong by one offset.
As as result, the image was showing a checkers board instead of a chess board 😕
It's now fixed

📝 fix image in docs

---

docs/move.md
tests/AttackTest.php
tests/MoveTest.php

I removed some heavy string manipulations in data sources, just by applying it.
Small side-change in docs: fixed wording (I recently discovered that "information" is uncountable in English)

✅ small improvements in tests

---

.gitattributes
.php-cs-fixer.php
composer.json
phpbench.json

also, fix configuration of phpbench and update phpunit-speedtrap

⬆️ update php-cs-fixer

---

src/Board.php

I just discovered (thanks to phpstorm suggestions) that we had a couple of badly implemented methods.
This is fixing them

🎨 fix Board
